                    ->link_js('/laguadmin/lib/fusion-charts/FusionCharts')
                    ->link_js('/laguadmin/js/jquery.microaccordion')
//                          "/laguadmin/js/jquery-1.6.2.min.js",
//        "/laguadmin/lib/jquery-ui/jquery-ui-1.8.15.custom.min.js",
//        "/laguadmin/lib/fusion-charts/FusionCharts.js",
//        "/laguadmin/js/jquery.microaccordion.js",
        "/laguadmin/js/jquery.tools.min.js",
        "/laguadmin/js/jquery.stickyPanel.js",
        "/laguadmin/js/jquery.text-overflow.min.js",
        "/laguadmin/js/xbreadcrumbs.js",
        "/laguadmin/js/lagu.js",
                                  
                                          "/laguadmin/js/jquery-1.6.2.min.js",
        "/laguadmin/js/jquery.tools.min.js",
        "/laguadmin/lib/jquery-validation/jquery.validate.js",
        "/laguadmin/js/login.js",
        "/laguadmin/js/lagu.js",
                                  
                                          "/laguadmin/js/jquery-1.6.2.min.js",
        "/laguadmin/lib/jquery-ui/jquery-ui-1.8.15.custom.min.js",
//        "/laguadmin/lib/fusion-charts/FusionCharts.js",
//        "/laguadmin/js/jquery.microaccordion.js",
        "/laguadmin/js/jquery.tools.min.js",
        "/laguadmin/js/jquery.stickyPanel.js",
        "/laguadmin/js/jquery.text-overflow.min.js",
        "/laguadmin/js/xbreadcrumbs.js",
        "/laguadmin/js/lagu.js",
                                          "/laguadmin/js/jquery-1.6.2.min.js",
        "/laguadmin/lib/jquery-ui/jquery-ui-1.8.15.custom.min.js",
        "/laguadmin/lib/harvesthq-chosen/chosen.jquery.min.js",
//        "/laguadmin/lib/fusion-charts/FusionCharts.js",
        "/laguadmin/lib/fancybox/jquery.easing-1.3.pack.js",
        "/laguadmin/lib/fancybox/jquery.fancybox-1.3.4.pack.js",
        "/laguadmin/lib/file-uploader/fileuploader.js",
        "/laguadmin/lib/tiny-mce/jquery.tinymce.js",
//        "/laguadmin/js/jquery.microaccordion.js",
        "/laguadmin/js/jquery.tools.min.js",
        "/laguadmin/js/jquery.stickyPanel.js",
        "/laguadmin/js/xbreadcrumbs.js",
        "/laguadmin/lib/jquery-validation/jquery.validate.js",
        "/laguadmin/lib/styled-checkboxes/iphone-style-checkboxes.js",
        "/laguadmin/lib/jquery-raty/jquery.raty.min.js",
        "/laguadmin/lib/timepicker-addon/jquery-ui-timepicker-addon.js",
        "/laguadmin/js/lagu.js",
                                  
                                          "/laguadmin/js/jquery-1.6.2.min.js",
//        "/laguadmin/lib/fusion-charts/FusionCharts.js",
//        "/laguadmin/js/jquery.microaccordion.js",
        "/laguadmin/js/jquery.stickyPanel.js",
        "/laguadmin/js/xbreadcrumbs.js",
        "/laguadmin/lib/slidernav/slidernav.js",
        "/laguadmin/js/lagu.js",
        
        "/laguadmin/lib/jquery-ui/jquery-ui-1.8.15.custom.min.js",
        "/laguadmin/lib/harvesthq-chosen/chosen.jquery.min.js",
        "/laguadmin/lib/fancybox/jquery.easing-1.3.pack.js",
        "/laguadmin/lib/fancybox/jquery.fancybox-1.3.4.pack.js",
        "/laguadmin/lib/tiny-mce/jquery.tinymce.js",
        "/laguadmin/js/jquery.tools.min.js",
        
        "/laguadmin/lib/datatables/jquery.dataTables.min.js",
        "/laguadmin/lib/datatables/dataTables.plugins.js",
        "/laguadmin/lib/timepicker-addon/jquery-ui-timepicker-addon.js",
                                  
                                          "/laguadmin/js/jquery-1.6.2.min.js",
        "/laguadmin/lib/jquery-ui/jquery-ui-1.8.15.custom.min.js",
        "/laguadmin/lib/harvesthq-chosen/chosen.jquery.min.js",
//        "/laguadmin/lib/fusion-charts/FusionCharts.js",
        "/laguadmin/lib/fancybox/jquery.easing-1.3.pack.js",
        "/laguadmin/lib/fancybox/jquery.fancybox-1.3.4.pack.js",
        "/laguadmin/lib/file-uploader/fileuploader.js",
        "/laguadmin/lib/tiny-mce/jquery.tinymce.js",
//        "/laguadmin/js/jquery.microaccordion.js",
        "/laguadmin/js/jquery.tools.min.js",
        "/laguadmin/js/jquery.stickyPanel.js",
        "/laguadmin/js/xbreadcrumbs.js",
        "/laguadmin/lib/jquery-validation/jquery.validate.js",
        "/laguadmin/lib/styled-checkboxes/iphone-style-checkboxes.js",
        "/laguadmin/lib/jquery-raty/jquery.raty.min.js",
        "/laguadmin/lib/timepicker-addon/jquery-ui-timepicker-addon.js",
        "/laguadmin/js/lagu.js",